---
id: "Control.Accordion"
parent_id: "Control"
type: class
line_number: 11
description: |
  Stacked title bars slide up and down to reveal different
  sections of content.

file: ./src/accordion/accordion.js